# __________________________________________________
#
# Workflow to compile and run minipic
# __________________________________________________

name: minipic

run-name: Test minipic

on: [push]

jobs:

  sequential:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: environment
      run: |
        python -m pip install --upgrade pip
        pip3 install numpy

    - name: Compile and run minipic sequential
      run: |
        cp -r tests sequential
        cd sequential
        python run.py -c g++ -g sequential

  openmp:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: environment
      run: |
        python -m pip install --upgrade pip
        pip3 install numpy

    - name: Compile and run minipic openmp loop
      run: |
        cp -r tests openmp_loop
        cd openmp_loop
        python run.py -c g++ -g openmp

  openmp_task:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: environment
      run: |
        python -m pip install --upgrade pip
        pip3 install numpy
        sudo apt-get install g++-13
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 13

    - name: Compile and run minipic openmp task
      run: |
        cp -r tests openmp_task
        cd openmp_task
        python run.py -c g++ -g openmp_task
