# __________________________________________________
#
# Workflow to compile and run minipic
# __________________________________________________

name: minipic

run-name: Test minipic

on: [push]

jobs:

  sequential:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile and run minipic
      run: |
        cd tests
        python run.py -c g++ -g sequential
